### PR TITLE
[v.1.2.5] Dev

### PR DESCRIPTION
**Pull request by tintinkung**
everything.

### CODE REVIEW

**Comment by StoneMcYT** [comment]
I see we are getting ready to push.

@tintinkung  is it okay if i make a few minor capitalization hotfix. As some people want the caps to be fixed.

**Comment by tintinkung** [comment]
> @tintinkung is it okay if i make a few minor capitalization hotfix. As some people want the caps to be fixed.

ye do it but don’t merge yet

**Comment by tintinkung** [comment]
@StoneMcYT mostly ready, need u to double check the previewed web and find bugs then approve the pr
so i can merge to main

**Review by StoneMcYT — APPROVED** [review]
Looks good for public beta release lets :shipit:

**Pull request merged**
